-- AlterTable
ALTER TABLE "PrintingOrder" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Profile" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "QRCode" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Vendor" ALTER COLUMN "id" DROP DEFAULT;
